CREATE TABLE EMP_TABLE (EMP CHAR(4), MANAGER CHAR(4), PHONE VARCHAR(8));

INSERT INTO EMP_TABLE VALUES ('대표', NULL, '0000');
INSERT INTO EMP_TABLE VALUES ('영업이사','대표','1111');
INSERT INTO EMP_TABLE VALUES ('관리이사','대표','2222');
INSERT INTO EMP_TABLE VALUES ('정보이사','대표','3333');
INSERT INTO EMP_TABLE VALUES ('영업과장','영업이사','1111-1');
INSERT INTO EMP_TABLE VALUES ('경리부장','관리이사','2222-1');
INSERT INTO EMP_TABLE VALUES ('인사부장','관리이사','2222-2');
INSERT INTO EMP_TABLE VALUES ('개발팀장','정보이사','3333-1');
INSERT INTO EMP_TABLE VALUES ('개발주임','정보이사','3333-1-1');

COMMIT;
SELECT * FROM EMP_TABLE;

SELECT 직원.EMP, 직원.MANAGER, 직원.PHONE, 매니저.PHONE 매니저의전화번호 FROM EMP_TABLE 직원 JOIN EMP_TABLE 매니저
ON 직원.MANAGER = 매니저.EMP AND 매니저.EMP = '정보이사';