SELECT MEM_ID, MEM_NAME, ADDR FROM MEMBER;

CREATE VIEW V_MEMBER AS (SELECT  MEM_ID, MEM_NAME, ADDR FROM MEMBER);

SELECT * FROM V_MEMBER;

SELECT * FROM V_MEMBER WHERE MEM_NAME = '블랙핑크';

CREATE VIEW V_MEMBERBUY AS (SELECT B.MEM_ID, M.MEM_NAME, B.PROD_NAME, M.ADDR
							FROM BUY B JOIN MEMBER M ON B.MEM_ID = B.MEM_ID);

SELECT * FROM V_MEMBERBUY;

-- 수정
CREATE OR REPLACE VIEW V_MEMBERBUY AS (SELECT B.MEM_ID, M.MEM_NAME, B.PROD_NAME, M.ADDR, CONCAT(M.PHONE1 , M.PHONE2) PHONE
							FROM BUY B JOIN MEMBER M ON B.MEM_ID = B.MEM_ID);

-- 업데이트
UPDATE V_MEMBER SET ADDR = '부산' WHERE MEM_ID = 'BLK';
SELECT * FROM V_MEMBER;
SELECT * FROM MEMBER; -- 뷰가 참조하는 MEMBER 테이블의 데이터도 자동으로 변경

INSERT INTO V_MEMBER(MEM_ID, MEM_NAME, ADDR) VALUES('BST','방탄소년단','경기'); -- 뷰가 참조하는 MEMBER테이블의 MEM_NUMBER가 NN이므로 반드시 입력되어야한다
/*
VIEW에 NN인 MEM_NUMBER도 추가해서 만들거나, MEMBER TABLE에 직접 INSERT해야함
*/
DESC MEMBER;